apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplikacja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aplikacja
  template:
    metadata:
      labels:
        app: aplikacja
    spec:
      containers:
        - name: aplikacja
          image: aplikacja:latest # Zastąp nazwą swojego obrazu
          imagePullPolicy: Never # NAJWAZNIEJSZE aby korzystac z lokalnego Image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://database:5432/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: mypassword