apiVersion: v1
kind: Service
metadata:
  name: aplikacja-nodeport
spec:
  type: NodePort
  selector:
    app: aplikacja
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
